### ISSUE TITLE
Error: Could not find a definition

### ISSUE THREAD

**Issue by psyrendust** [marijnh/tern_for_sublime#19]
With the following code sample, placing my cursor in the middle of the function `doSomething` on line 4 `foo.doSo[cursor here]mething('one', 'two');` hitting `alt+.` returns **Error: Could not find a definition**

```js
function Thing(){}
Thing.prototype.doSomething = function(arg1, arg2) {};
var foo = new Thing();
foo.doSomething('one', 'two');
```

**Comment by marekkaczkowski** [comment]
Should ternjs jump to requirejs defined resource like in demo editor (test_dep.js)?

**Comment by marijnh** [comment]
Can you give me an example project where the requirejs plugin fails to find the proper file?

**Comment by psyrendust** [comment]
@marijnh I'd like to go ahead and close this issue. Would you be ok with that?

**Comment by marijnh** [comment]
Yes, let's close
