### ISSUE TITLE
Display tern_argument_hints in the popup

### ISSUE THREAD

**Issue by dani-h** [marijnh/tern_for_sublime#47]
Is it possible to display the argument hints and return values in the popup? Right now, the string that displays on the small bottom panel is not very intuitive.

There are two alternatives to this:
a) Display the arguments and return values at the same time as the function suggestion is being displayed in the tooltip.
b) Display the arguments and return values when the user enters the parenthesis, just like it works now, except that the values are displayed in the status panel.

**Comment by subhaze** [comment]
@dani-h @PixelT @AnAppAMonth ST 3 received a proper tooltip API today and I've a WIP pull request in progress, hopefully this will solve some of the concerns raised on this thread. #61

**Comment by dani-h** [comment]
:+1:

**Comment by marijnh** [comment]
I think #61 resolves this.
