### ISSUE TITLE
sublime empty error message

### ISSUE THREAD

**Issue by gertcuykens** [marijnh/tern_for_sublime#55]
I get allot of this when editing scripts in html

![screen shot 2014-12-30 at 00 26 16](https://cloud.githubusercontent.com/assets/863731/5574278/e76300d4-8fba-11e4-8232-2f6dc48e4453.png)

**Comment by marijnh** [comment]
> hmm I don't see anything happening?

Did you kill existing Tern instances before running the server from the command line? And are you in the directory that the file you are editing is also in? For me, running the server does cause Sublime Text to connect to it, and I can see the `--verbose` output.

I still wasn't able to reproduce this, even when I create an html file with an unclosed script tag in it.

**Comment by gertcuykens** [comment]
ok i will close this for now until I have time for a more solid example.

**Comment by herron9** [comment]
I saw the same issue today and it just begins to happen without any change. Any one has idea how to solve it? Tried disable Tern and reinstall, but that does not work.
