### ISSUE TITLE
autosave closes autocomplete menu and overwrites the status message

### ISSUE THREAD

**Issue by gertcuykens** [marijnh/tern_for_sublime#56]
Is there a way to prevent autosave to close the autocomplete menu and overwriting the status bar message?

**Comment by marijnh** [comment]
Does it not do this when you are using other autocomplete packages? I can't see anything that would cause this in the plugin's code, but I don't have enough experience with sublime text scripting to really know why it could happen.

**Comment by gertcuykens** [comment]
Yes other autocomplete packages close it too :) really enoying

**Comment by marijnh** [comment]
Okay. I agree that's awful, but it seems to be an ST bug, not something I can help.
