### ISSUE TITLE
Lazy file loading

### ISSUE THREAD

**Issue by zeird** [marijnh/tern_for_sublime#58]
I have a `test` folder with 2 files: `a.js` and `b.js`:
`a.js` contents:

    var obj_a = {
        test_a: function() {}
    };

`b.js` contents:

    var obj_b = {
        test_b: function() {}
    };

I open those two files, enter `obj_` in `a.js` and there's not `obj_b`: ![pic. 1](http://i.imgur.com/oFtL2Vq.png)

Ok, I switch to `b.js`. It has `obj_a` in auto-completion list: ![pic. 2](http://i.imgur.com/kAyNWFV.png)
Sometimes there are objects from both files in auto-completion list in file `a.js`, and there's only `obj_b` in `b.js`, like `b.js` was loaded in `tern` and `a.js` wasn't. It seems like I have to show some activity in one file for it to load in `tern`, like entering a text, trigger auto-completion or saving it. I don't know.

**Comment by marijnh** [comment]
Yes, files are only pushed to the inference engine when:

 - They are specified in the `loadEagerly` project option
 - They are pulled in by some dependency management plugin
 - You run a query on them from your editor

In your situation, I think adding a `loadEagerly` option (maybe using wilcards, like `test/*.js`), is the way to go.

**Comment by zeird** [comment]
>You run a query on them from your editor

Thanks for the answer. But the [docs](http://ternjs.net/doc/manual.html#configuration) say that

>By default, local files are loaded into the Tern server when they are opened by the editor.

which turns out to be untrue. Maybe you should edit that sentence about file loading and specify that conditions?

**Comment by marijnh** [comment]
That's a good point. Attached patch should help there.
