### ISSUE TITLE
Argument hints

### ISSUE THREAD

**Issue by tjoskar** [marijnh/tern_for_sublime#59]
Hi,

First of all I want to thank you, @marijnh, for a fantastic job with ternJS, it's awesome (and I can't wait for ES6 support, I will gladly fund it).

However, I have some problem to get argument hints for function call, see my gif:

![pkvhuzmadc](https://cloud.githubusercontent.com/assets/1525612/6096107/89e86c88-af80-11e4-884c-1f581a7e22a9.gif)

Do I miss something?
My `Preferences.sublime-settings` contains the following lines:
```json
"tern_command": [
    "/usr/local/bin/node",
    "/absoult_path_to/Packages/tern_for_sublime/node_modules/tern/bin/tern"
],
"tern_argument_hints": true,
```

My `.tern-project`:
```json
{
  "plugins": {
    "doc_comment": {
      "fullDocs": true
    }
  }
}
```

In brackets I get the following (expected) result:
![yrgovnvgs0](https://cloud.githubusercontent.com/assets/1525612/6096122/4d13c1f8-af81-11e4-8998-929a491d2209.gif)

**Comment by marijnh** [comment]
Your setting looks entirely correct, and given the fact that you are getting proper completions, I can't explain why the argment hints are not showing up. Maybe try adding debug output (Python `print` statements will end up in the ctrl-~ console) to the plugin code, to see whether `arghints_enabled` ends up being set to True, and whether `show_argument_hints` is being called, etcetera.

**Comment by subhaze** [comment]
FWIW, argument hints are working for me.

latest ST 3 dev build
latest tern_for_sublime release
OS X 10.8

**Comment by tjoskar** [comment]
Nice, I have tried it on an other computer (`build 3070`) and it works like a charm. I will however wait for `build 3070` to be released as non-dev-preview before I use it. I close this ticket in the meanwhile.

**Comment by chris--** [comment]
+1 on the problem of non-showing argument hints in both, build 3065 and 3079 despite setting `tern_argument_hints`

![bildschirmfoto 2015-03-23 um 23 12 24](https://cloud.githubusercontent.com/assets/1640619/6791778/1ade75f4-d1b2-11e4-928a-2c924ca09d85.png)

**Comment by subhaze** [comment]
@chris-- argument hints wont appear until you're within the `(..)` of the function.

The screenshot provided shows the correct behavior.

**Comment by chris--** [comment]
@subhaze ah, i see. Apparently, it does work on dev build 3079! Thanks for the quick response.
