### ISSUE TITLE
Doesn't load files no listed in the" loadEagerly" .tern-project file

### ISSUE THREAD

**Issue by TimothyWrightSoftware** [marijnh/tern_for_sublime#60]
I have gotten everything to work except that only files in the "loadEagerly" path can be found.  Is there a setting for looking within other folders for lazy loading that I am missing?

**Comment by marijnh** [comment]
What do you mean by lazy loading? Files are loaded when you set them to be loaded eagerly, when you interact with them though your editor, or when a dependency-management plugin decides another file depends on them. There is no other mechanism for loading them.

**Comment by TimothyWrightSoftware** [comment]
That was my question.  It wasn't clear to me what causes a file to be loaded.  I didn't see any mention of a dependency-management plugin in the docs.  Could you please point me to that section?

**Comment by marijnh** [comment]
Plugins for [node](http://ternjs.net/doc/manual.html#plugin_node) and [requirejs](http://ternjs.net/doc/manual.html#plugin_requirejs) try to automatically notice and load dependencies.
