### ISSUE TITLE
Enable for babel javascript syntax

### ISSUE THREAD

**Issue by tinkertrain** [marijnh/tern_for_sublime#71]
Hello!

First of all thanks for the great work on the plugin.

I was just wondering if it's possible to enable it when using a different JS syntax highlighter? I'm using the Babel JS one (which is superior than the normal one and supports es6 much better), if it is, how would I do it?

Thanks!

**Comment by marijnh** [comment]
I did not think useage of Tern was in any way related to the highlighter you use (but then, I don't know much about Sublime). Does the Babel highlighter cause a different selector (as in `source.js`) to be applied to JS code?

**Comment by wavded** [comment]
@tinkertrain I use babel syntax highlighting with tern without issue.  Tern really doesn't have anything to do with what syntax scheme you select in my experience.

**Comment by tinkertrain** [comment]
You are right! Thanks a lot I think I had another unrelated issue....
