### ISSUE TITLE
JSDoc: hide @param and @return tags in description

### ISSUE THREAD

**Issue by denis-sokolov** [marijnh/tern_for_sublime#76]
When showing a description for the function, Tern shows unexpectedly much.
I can see the `@param` and `@return` tags in the types of the appropriate arguments, and the resulting popup is quite messy due to their inclusion. Would it be possible to simplify it?

Observed behavior:
![1](https://cloud.githubusercontent.com/assets/113721/8146922/3bf3cf96-125d-11e5-8aa4-280a69904c57.png)

Expected behavior:
![2](https://cloud.githubusercontent.com/assets/113721/8146930/aae7d014-125d-11e5-8be9-f5b0f32b467a.png)

Thank you!
(Also see [the discussion in tern.js server issue](https://github.com/marijnh/tern/issues/563), yes, I realize the main author is the same :)).

**Comment by marijnh** [comment]
Attached patch should move the default behavior back to (something very close to) the old behavior. Does this solve your problem?

**Comment by denis-sokolov** [comment]
Yes, this works great. Thank you!

**Comment by max-mykhailenko** [comment]
@denis-sokolov please show your `.tern-project`, I have unexpected freezing with my config https://github.com/marijnh/tern_for_sublime/issues/37

**Comment by denis-sokolov** [comment]
I'm sorry, what does that have to do with the issue?

**Comment by max-mykhailenko** [comment]
@denis-sokolov problem appear only when I add `loadEagerly` section to my config. 

```
"loadEagerly" : [
    "**/*.js",
    "**/*.jsx"
  ],
```
Seems it's jsx fault.

But without jsx I also didn't have so detailed tooltip.
